---
title: "Week2_HW_PL"
output: html_document
---
```{r}
library(readxl)
library(ggplot2)
library(forecast)
library(fpp2)
```
#6.2
##A
```{r}
autoplot(plastics)
```
```{r}
decompose_plastics <- decompose(plastics,
                                type = "multiplicative")
autoplot(decompose_plastics)
```
#C
```{r}

```
#D
```{r}
autoplot(plastics, series="Data") +
  autolayer(trendcycle(decompose_plastics), series="Trend") +
  autolayer(seasadj(decompose_plastics), series="Seasonal Data") +
  xlab("Year") + ylab("Monthly Sales") +
  ggtitle("Sales of plastic products") +
  scale_colour_manual(values=c("gray","blue","black"),
                     breaks=c("Data","Seasonal Data","Trend"))
```
#E
```{r}
plastics_outlier  <- plastics
plastics_outlier [50] <- plastics_outlier [50] + 500
decompose_plastics_outlier<- decompose(
  plastics_outlier,
  type = "multiplicative"
  )
autoplot(plastics_outlier, series="Data") +
  autolayer(trendcycle(decompose_plastics_outlier), series="Trend") +
  autolayer(seasadj(decompose_plastics_outlier), series="Seasonal Data") +
  xlab("Year") + ylab("Monthly Sales") +
  ggtitle("Sales of plastic products") +
  scale_colour_manual(values=c("gray","blue","black"),
                     breaks=c("Data","Seasonal Data","Trend"))
```
#F
```{r}
plastics_outlier2  <- plastics
plastics_outlier2 [10] <- plastics_outlier2 [10] + 500
decompose_plastics_outlier2<- decompose(
  plastics_outlier2,
  type = "multiplicative"
  )
autoplot(plastics_outlier2, series="Data") +
  autolayer(trendcycle(decompose_plastics_outlier2), series="Trend") +
  autolayer(seasadj(decompose_plastics_outlier2), series="Seasonal Data") +
  xlab("Year") + ylab("Monthly Sales") +
  ggtitle("Sales of plastic products") +
  scale_colour_manual(values=c("gray","blue","black"),
                     breaks=c("Data","Seasonal Data","Trend"))
```

#6.6
##A
```{r}
# STL decomposition fixed seasonality
fixed_stl <- stl(bricksq, 
                          s.window = "periodic",
                          robust = TRUE)
# STL decomposition changing seasonality
changing_stl <- stl(bricksq,
                             s.window = 8,
                             robust = TRUE)
```
```{r}
#Plot Data
autoplot(fixed_stl) +
  ggtitle('Brick STL Fixed')
autoplot(changing_stl) +
  ggtitle('Brick STL Changing')
```
##B
```{r}
# fixed seasonality
autoplot(bricksq, series = 'Data') +
  autolayer(seasadj(fixed_stl),
            series = 'Seasonal Data') +
  autolayer(trendcycle(fixed_stl),
            series = 'Trend cycle') +
  ggtitle('Australian quarterly clay brick production. 1956-1994',
          subtitle = 'decomposed using STL with fixed seasonality') +
  scale_color_manual(values = c('gray', 'blue', ' black'),
                     breaks = c('Data', 'Seasonal Data','Trend cycle'))
# changing seasonality
autoplot(bricksq, series = 'Data') +
  autolayer(seasadj(changing_stl),
            series = 'Seasonal Data') +
  autolayer(trendcycle(changing_stl),
            series = 'Trend cycle') +
  ggtitle('Australian quarterly clay brick production. 1956-1994',
          subtitle = 'decomposed using STL with changing seasonality') +
  scale_color_manual(values = c('gray', 'blue', ' black'),
                     breaks = c('Data', 'Seasonal Data','Trend cycle'))
```
##C
```{r}
fixed_stl %>% seasadj() %>% naive() %>% autoplot() + 
  ggtitle(label = "Naive forecast for seasonally adjusted brick data",
          subtitle = "decomposed using STL with fixed seasonality")
changing_stl %>% seasadj() %>% naive() %>% autoplot() + 
  ggtitle(label = "Naive forecast for seasonally adjusted brick data",
          subtitle = "decomposed using STL with changing seasonality")
```
##D
```{r}
stlf_brick <- stlf(bricksq)
autoplot(stlf_brick)
```
##E
```{r}
checkresiduals(stlf_brick)
```
#F
```{r}
stlf_brick_robust <- stlf(bricksq, robust = TRUE)
autoplot(stlf_brick_robust)
checkresiduals(stlf_brick_robust)
```
##G
```{r}
train_data <- subset(bricksq, 
                        end = length(bricksq) - 7)
test_data <- subset(bricksq,
                        start = length(bricksq) - 9)
snaive_brick <- snaive(train_data)
stlf_brick_part <- stlf(train_data, robust = TRUE)

autoplot(bricksq, series = "Original") +
  geom_line(size = 1) +
  autolayer(stlf_brick_part, PI = FALSE, size = 1,
            series = "stlf forecast") +
  autolayer(snaive_brick, PI = FALSE, size = 1,
            series = "snaive forecast") +
  scale_color_manual(values = c("gray", "blue", "green"),
                     breaks = c("Original", "stlf forecast", "snaive forecast")) +
  scale_x_continuous(limits = c(1990, 1994.5)) +
  scale_y_continuous(limits = c(350, 550)) +
  guides(colour = guide_legend(title = "Data")) +
  ggtitle("Forecast comparison between stlf and snaive functions") +
  annotate(
    "rect",
    xmin=1993,xmax=1994.5,ymin=-Inf,ymax=Inf,
    fill="light blue",alpha = 0.5
    )
```