---
title: "Week3_HW_PL"
output: html_document
---
#3.1
```{r}
suppressMessages(suppressWarnings(library(mlbench)))
suppressMessages(suppressWarnings(library(dplyr)))
suppressMessages(suppressWarnings(library(tidyr)))
suppressMessages(suppressWarnings(library(knitr)))
suppressMessages(suppressWarnings(library(ggplot2)))
```
```{r}
data(Glass)
str(Glass)
```
##a
```{r}
Glass
```
```{r}
ggplot(Glass,aes(x=Type))+
  geom_bar(colour="black")+
  ggtitle("Observation Count by Glass Type")
```
```{r}
for(i in 1:9){
  x <- Glass[,i]
   hist(x,
       main=paste("Series Chart",i,": Box Plot of Chemical Elements",
          names(Glass)[i],"by Type of Glass"),
       xlab="Type of Glass",
       col = ("Dark Green"))
}
```
#3.2
```{r}
data(Soybean)
```

```{r}
Soybean
```
##A
```{r}
na_count <-sapply(Soybean, function(y) sum(length(which(is.na(y)))))
na_count <- data.frame(na_count)
na_count$names <- rownames(na_count)
na_count
```
```{r}
ggplot(data=na_count) + geom_point(aes(x=na_count,y=names))
```
##B
```{r}
#Seed, Fruit, and Leef data seems to be the most scarce
```
##C
```{r}
Soybean_NA_Fix<- Soybean[is.na(Soybean)] <- 0
Soybean_NA_Fix

na_count_2 <-sapply(Soybean, function(y) sum(length(which(is.na(y)))))
na_count_2 <- data.frame(na_count_2)
na_count_2$names <- rownames(na_count_2)
na_count_2
```