---
title: "624_Week1"
output: html_document
---
```{r}
library(readxl)
library(ggplot2)
library(forecast)
library(fpp2)
```
#2.3
##a
Import data
```{r}
retaildata <- readxl::read_excel("retail.xlsx", skip=1)
```
review data
```{r}
head(retaildata)
```
##b
select a time series
```{r}
myts <- ts(retaildata[,"A3349503T"],
  frequency=12, start=c(1982,4))
```
##c
Analysis

The autoplot and ggseason plot show the clearest trends. It appears it appears as though the trend is cyclical, peaking in the winter months. However, there is also an upward trend as the data moves closer to more recent years. 
```{r}
autoplot(myts)
ggseasonplot(myts)
ggsubseriesplot(myts)
gglagplot(myts)
ggAcf(myts)
```

#2.7
Plot and analyze 'arrivals' data set. 
```{r}
arrivals <- ts(arrivals, frequency=4, start=c(1981,1))
head(arrivals)
```

```{r}
autoplot(arrivals)
```

```{r}
ggseasonplot(arrivals[,1]) 
ggseasonplot(arrivals[,2]) 
ggseasonplot(arrivals[,3]) 
ggseasonplot(arrivals[,4]) 
```
```{r}
ggsubseriesplot(arrivals[,1]) 
ggsubseriesplot(arrivals[,2]) 
ggsubseriesplot(arrivals[,3]) 
ggsubseriesplot(arrivals[,4]) 
```
```{r}
gglagplot(arrivals[,1]) 
gglagplot(arrivals[,2]) 
gglagplot(arrivals[,3]) 
gglagplot(arrivals[,4])
```
```{r}
ggAcf(arrivals)
```
#2.10
```{r}
ddj <- diff(dj)
autoplot(ddj)
```
#3.1
```{r}
plot(usnetelec); plot(BoxCox(usnetelec,lambda=1/2))
plot(usgdp); plot(BoxCox(usgdp,lambda=0))
plot(mcopper); plot(BoxCox(mcopper,lambda=1/3))
plot(enplanements); plot(BoxCox(enplanements,lambda=0))
```
#3.8
```{r}
myts.train <- window(myts, end=c(2010,12))
myts.test <- window(myts, start=2011)
autoplot(myts) +
autolayer(myts.train, series="Training") +
autolayer(myts.test, series="Test")
fc <- snaive(myts.train)
accuracy(fc,myts.test)
checkresiduals(fc)
```