---
title: "Week4_HW_PL"
output: html_document
---
```{r}
suppressMessages(suppressWarnings(library(readxl)))
suppressMessages(suppressWarnings(library(ggplot2)))
suppressMessages(suppressWarnings(library(forecast)))
suppressMessages(suppressWarnings(library(fpp2)))
suppressMessages(suppressWarnings(library(mlbench)))
suppressMessages(suppressWarnings(library(caret)))
suppressMessages(suppressWarnings(library(caTools)))
```
#7.5
##A
```{r}
data(books)
head(books)
autoplot(books)
```
##B
```{r}
Books_Forecast <- ses(books[1:30], h=30, alpha=0.1, initial="simple")
Books_Forecast
plot(Books_Forecast)
```
##C
```{r}
model <- train(Paperback ~ Hardcover, books,
               method = "lm",
               trControl = trainControl(
                 method = "cv",
                 number = 10,
                 verboseIter = T
               ))
model
```
#7.6
```{r}
holt_Paper <- holt(books[,1], initial = "simple", h=4)
summary(holt_Paper)
plot(holt_Paper)
```
```{r}
holt_Hardcover <- holt(books[,2], initial = "simple", h=4)
summary(holt_Hardcover)
plot(holt_Hardcover)
```
#7.10
```{r}
data(ukcars)
head(ukcars)
```
##A
```{r}
autoplot(ukcars)
```
##B
```{r}
decomposed <- stl(ukcars, s.window="periodic", robust=TRUE)
seasonal <- decomposed$time.series[,1]

cars_stl <- ukcars - seasonal
cars_stl
autoplot(cars_stl)
```
##C
```{r}
stlf_decompose_ukcars <- stlf(cars_stl, etsmodel="AAN", damped=TRUE)
stlf_decompose_ukcars
```
##D
```{r}
holt1 <- holt(cars_stl, h=8, damped = TRUE)

lastyear <- rep(decomposed$time.series[110:113,"seasonal"],2)
reseasonalized_fc <- holt1$mean + lastyear

summary(holt1)
holt1
autoplot(holt1)
```
```{r}
holt2 <- holt(cars_stl, h=8)
reseasonalized_fc <- holt2$mean + lastyear
summary(holt2)
autoplot(holt2)
```
##E
```{r}
fit3 <- ets(cars_stl)
summary(fit3)
```
##F
```{r}
#Needs review
print("Accuracy of STL + ETS(A, Ad, N) model")
accuracy(stlf_ets_AAdN_ukcars)
print("Accuracy of STL + ETS(A, A, N) model")
accuracy(stlf_ets_AAN_ukcars)
print("Accuracy of ETS(A, N, A) model")
accuracy(ets_ukcars)
# STL + ETS(A, Ad, N) was the best model.

```
##G
```{r}
plot(holt1); plot(holt2) ; plot(fit3)
```
##H
```{r}
#row.names(holt1) <- holt1$Point_Forecast
holt1.res = resid(holt1)
autoplot(holt1$upper)
autoplot(holt1.res)
```